CC = gcc # Compilador
CFLAGS = -I./src -I./src/cJSON # Opciones de compilación
SRC = src/main.c src/json.c src/cJSON/cJSON.c # Archivos fuente
LDFLAGS = # Opciones de enlace

all: $(TARGET) # Compilación del objetivo

$(TARGET): $(SRC) # Regla para compilar el objetivo y generación del ejecutable
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS) 

clean: # Limpieza de archivos generados
	rm -f build/main datos.json 

